#!/bin/sh
export TERM=${TERM:-dumb}
clear
echo 
echo
echo "Firmware Uploader Mac for Teensy3.1"
echo "                    C 2016 Safecast\n"
echo "  \n"
echo "  \n"


##############################################################################################

# DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)



##############################################################################################
#
# Now select the HEX file
#
##############################################################################################


  cd $DIR/hex
  files=$(ls *.hex)
  i=0
  for j in $files
  do
    i=$(( i + 1 ))
    file[i]=$j
  done

  if [ "$i" = 1 ] ; then
    input=1
    i=0
    for j in $files
    do
      i=$(( i + 1 ))
      # echo "$i. $j"
    done
  fi



##############################################################################################
#
# Now do the business
#
##############################################################################################


echo $'\n'



  cd $DIR
./teensy_loader_cli --mcu=mk20dx256 -w -v $DIR/hex/${file[$input]}

exit


